---
title: "Data Generation Process of base_indcp"
author: Kazuharu Yanagimoto
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data Generation Process of base_indcp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  dev = "svg",
  fig.ext = "svg"
)
```

```{r setup}
library(indcp)
library(tidyverse)
```

## Data Generation Process

The sample data set `base_indcp` is generated by `indcp::gen_data()` with seed `1234`.

```r
set.seed(1234)
base_indcp <- gen_data()
```

Inside of the function `gen_data()`, the following steps are performed.

Generate $i = \{1, \dots, 1000\}$ individuals with age at child birth $a_i$
from a multinomial distribution of $f(a)$.


$$
f(a) = \begin{cases}
\frac{a - 14}{15 \cdot 16} & \text{if } a \in \{15, \dots, 29\} \\
\frac{45 - a}{15 \cdot 16} & \text{if } a \in \{30, \dots, 44\} \\
\end{cases}
$$
```{r}
base_indcp |>
  summarize(n = n(), .by = cage) |>
  mutate(density = n / sum(n)) |>
  ggplot(aes(x = cage, y = density)) +
  geom_col() +
  labs(x = "Age at First Childbirth", y = "n") +
  theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())
```
```{r}
sum(seq(0, 1/16, length.out = 16)[2:16])
```

$$
\alpha_{i} \sim \mathcal{N}(0, 1) \\
$$






## Unbiasedness and Consistency of the Estimator

### Mean of $\tau_{ik}$

### Variance of $\tau_{ik}$








