#' Generate Sample Data
#'
#' @return A sample dataframe with heterogenous child penalty over the age at first birth
#' @export
#'
#' @examples
#' set.seed(1234)
#' base_indcp <- gen_data()
#'
gen_data <- function() {

  year_start <- 1999
  year_end <- 2016
  cyear_end <- 2021
  size_cohort <- 1000
  byear_start <- 1965
  byear_end <- 1984
  cage_start <- 15
  cage_end <- 44
  prob_cage <- c(seq(0, 1/16, length.out = 16)[2:16],
                 seq(1/16, 0, length.out = 16)[1:15])
  k_start <- 0
  k_end <- 5

  n_b <- byear_end - byear_start + 1
  N <- size_cohort * n_b
  n_year <- year_end - year_start + 1

  mean_alpha <- 0.15
  sd_alpha <- 0.1
  lambdas <- stats::rnorm(n_year, 0, 0.1)
  mean_epsilon <- 0
  sd_epsilon <- 0.025

  df_ind <- dplyr::tibble(
    id = 1:N,
    alpha = stats::rnorm(N, mean_alpha, sd_alpha),
    byear = rep(byear_start:byear_end, each = size_cohort),
    cage = sample(cage_start:cage_end, N,
                  replace = TRUE, prob = prob_cage),
    cyear = byear + cage,
    sd1 = 2.892 - 0.797 * log(cage)) |>
    dplyr::mutate(sd1 = dplyr::if_else(sd1 < 0.1, 0.1, sd1),
           tau1 = -1.143 + 0.313 * log(cage))

  df_full <- df_ind |>
    dplyr::slice(rep(1:dplyr::n(), each = n_year)) |>
    dplyr::mutate(
      year = rep(year_start:year_end, time = N),
      lambda = rep(lambdas, time = N),
      epsilon = stats::rnorm(N * n_year, mean_epsilon, sd_epsilon),
      rel_time = year - cyear,
      sd_tmp = 0.006 + 1.051 * sd1 + 0.01 * rel_time,
      tau = dplyr::case_when(
         rel_time < 0 ~ 0,
         rel_time == 0 ~ tau1 / 3 + + stats::rnorm(N * n_year, 0, sd1 / 3),
         rel_time == 1 ~ tau1 + stats::rnorm(N * n_year, 0, sd1),
         rel_time > 1 ~ 0.038 + 1.444 * tau1 - 0.011 * rel_time +
           stats::rnorm(N * n_year, 0, dplyr::if_else(sd_tmp > 0, sd_tmp, 1e-9))),
      y = alpha + lambda + tau + epsilon)

  df_raw <- df_full |>
    dplyr::filter(cyear <= cyear_end) |>
    dplyr::select(id, year, byear, cage, rel_time, y) |>
    dplyr::mutate(is_treated = rel_time >= 0)

  return(df_raw)
}

#' Simulated Individual Child Panalty Data
#'
#' @format ## `base_indcp`
#' A dataframe with 1000 individuals for each birth year from 1965 to 1984:
#' \describe{
#'  \item{`id`}{Individual identifier}
#' \item{`year`}{Year of observation}
#' \item{`byear`}{Birth year}
#' \item{`cage`}{Age at first birth}
#' \item{`rel_time`}{Relative time to first birth}
#' \item{`y`}{Outcome variable}
#' }
#' @source Generated by `gen_data()` with seed `1234`
"base_indcp"