#' Generate Sample Heterogenous Child Penalty Data
#'
#' @param size_cohort n_obsumber of individuals per birth year
#' @return A sample dataframe with heterogenous child penalty over the age at first birth
#' @export
#'
#' @examples
#' set.seed(1234)
#' base_heterocp <- gen_heterocp()
#'
gen_heterocp <- function(size_cohort = 300) {
  
  # CRAN Errors
  byear = cage = sd1 = year = cyear = rel_time = alpha = lambda = tau = epsilon = NULL

  # Settings
  year_start <- 1999
  year_end <- 2021
  cage_start <- 15
  cage_end <- 44

  prob_cage <- c(seq(0, 1/16, length.out = 16)[2:16],
                 seq(1/16, 0, length.out = 16)[1:15])
  byear_start <- year_start - cage_end
  byear_end <- year_end - cage_start

  n_b <- byear_end - byear_start + 1
  n_obs <- size_cohort * n_b
  n_year <- year_end - year_start + 1

  mean_alpha <- 0.15
  sd_alpha <- 0.1
  lambdas <- stats::rnorm(n_year, 0, 0.1)
  mean_epsilon <- 0
  sd_epsilon <- 0.025

  df_ind <- dplyr::tibble(
    id = 1:n_obs,
    alpha = stats::rnorm(n_obs, mean_alpha, sd_alpha),
    byear = rep(byear_start:byear_end, each = size_cohort),
    cage = sample(cage_start:cage_end, n_obs,
                  replace = TRUE, prob = prob_cage)) |>
    dplyr::mutate(cyear = byear + cage,
                  sd1 = 3 - 0.75 * log(cage),
                  sd1 = dplyr::if_else(sd1 < 0.1, 0.1, sd1),
                  tau1 = -1.2 + 0.3 * log(cage))

  df_full <- df_ind |>
    dplyr::slice(rep(seq_len(dplyr::n()), each = n_year)) |>
    dplyr::mutate(
      year = rep(year_start:year_end, time = n_obs),
      lambda = rep(lambdas, time = n_obs),
      epsilon = stats::rnorm(n_obs * n_year, mean_epsilon, sd_epsilon),
      rel_time = year - cyear,
      sd_tmp = 0.01 + sd1 + 0.02 * rel_time,
      tau = dplyr::case_when(
         rel_time < 0 ~ 0,
         rel_time == 0 ~ tau1 / 3 + stats::rnorm(n_obs * n_year, 0, sd1 / 3),
         rel_time == 1 ~ tau1 + stats::rnorm(n_obs * n_year, 0, sd1),
         rel_time > 1 ~ 0.05 + 1.5 * tau1 - 0.02 * rel_time +
           stats::rnorm(n_obs * n_year, 0,
                        dplyr::if_else(sd_tmp > 0, sd_tmp, 1e-9))),
      y = alpha + lambda + tau + epsilon)

  df_raw <- df_full |>
    dplyr::filter(dplyr::between(year, year_start, year_end),
                  cyear <= year_end) |>
    dplyr::select("id", "year", "byear", "cyear", "y")

  return(df_raw)
}

#' Simulated Individual Child Panalty Data
#'
#' @format ## `base_heterocp`
#' A dataframe with 1000 individuals for each birth year from 1965 to 1984:
#' \describe{
#'  \item{`id`}{Individual identifier}
#' \item{`year`}{Year of observation}
#' \item{`byear`}{Birth year}
#' \item{`cage`}{Age at first birth}
#' \item{`rel_time`}{Relative time to first birth}
#' \item{`y`}{Outcome variable}
#' }
#' @source Generated by `gen_heterocp()` with seed `1234`
"base_heterocp"